#!/usr/bin/env bash
# This script transfers a file from our client to a server using scp
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# 1. PATH_TO_FILE: path to the file to be transferred
# 2. IP: IP of the server we want to transfer the file to
# 3. USERNAME: username scp connects with
# 4. PATH_TO_SSH_KEY: path to the private key that scp uses

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
