#!/usr/bin/env bash
# Backup hosts file
sudo cp /etc/hosts /etc/hosts.bak
# Change localhost IP
sudo sed -i 's/^127\.0\.0\.1/127.0.0.2/' /etc/hosts
# Change facebook.com IP
sudo sed -i 's/^.*facebook\.com/8.8.8.8 facebook.com/' /etc/hosts
# Restart networking service
sudo systemctl restart networking.service
